"""
Easy

1342

323

Add to List

Share
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
Example 3:

Input: s = "a", t = "aa"
Output: "a"
Example 4:

Input: s = "ae", t = "aea"
Output: "a"
 

Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lower-case English letters.
Accepted
268,276
Submissions
460,799
"""

"""
Runtime: 36 ms, faster than 60.20% of Python3 online submissions for Find the Difference.
Memory Usage: 14.2 MB, less than 82.85% of Python3 online submissions for Find the Difference.
"""

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        char_dict = {}
        for char in t:
            try:
                char_dict[char] += 1
            except KeyError:
                char_dict[char] = 1
        
        
        for char in s:
            
            if char_dict[char] == 1:
                char_dict.pop(char)
            else:
                char_dict[char] -= 1
        
        return next(iter(char_dict))
        
        